version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    stdin_open: true      # Аналог -i
    tty: true             # Аналог -t (без этого не будет интерактивности)
    command: /app/entrypoint
    networks:
      - observability-net

networks:
  observability-net:
    external: true


