version: '3.8'


services:
  # Jaeger для трассировки
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686"   # UI
      - "14268:14268"   # HTTP collector
      - "6831:6831/udp" # UDP receiver
    networks:
      - observability-net


  # Prometheus + Grafana
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability-net


  alertmanager:
    image: prom/alertmanager:v0.28.0
    restart: unless-stopped
    # копируем шаблон
    volumes:
      - ./configs/prometheus/alertmanager.template.yml:/etc/alertmanager/template.yml
      - ./scripts/alertmanager.sh:/alertmanager.sh
    ports:
      - "9093:9093"
    environment:
      - SMTP_USER=${SMTP_USER_MAIN}  # от кого слать уведомления
      - SMTP_RECEIVER=${SMTP_USER_MAIN} # кому слать уведомления
      - SMTP_PASSWORD=${SMTP_PASSWORD_LOYALTY_HUB} # пароль
    # делаем подстановку переменных окружения в шаблон конфига 
    entrypoint: /alertmanager.sh
    command: /bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - observability-net
    depends_on:
      - prometheus


networks:
  observability-net:
    driver: bridge
    name: observability-net

    
volumes:
  grafana-data:
